/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.tcc.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.Attribute#getAttributeName <em>Attribute Name</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.Attribute#getAttributeType <em>Attribute Type</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.Attribute#getDecisionGet <em>Decision Get</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.Attribute#getDecisionSet <em>Decision Set</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.Attribute#getDecisionID <em>Decision ID</em>}</li>
 * </ul>
 *
 * @see org.xtext.tcc.mydsl.myDsl.MyDslPackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Name</em>' containment reference.
   * @see #setAttributeName(AttributeName)
   * @see org.xtext.tcc.mydsl.myDsl.MyDslPackage#getAttribute_AttributeName()
   * @model containment="true"
   * @generated
   */
  AttributeName getAttributeName();

  /**
   * Sets the value of the '{@link org.xtext.tcc.mydsl.myDsl.Attribute#getAttributeName <em>Attribute Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Name</em>' containment reference.
   * @see #getAttributeName()
   * @generated
   */
  void setAttributeName(AttributeName value);

  /**
   * Returns the value of the '<em><b>Attribute Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Type</em>' containment reference.
   * @see #setAttributeType(AttributeType)
   * @see org.xtext.tcc.mydsl.myDsl.MyDslPackage#getAttribute_AttributeType()
   * @model containment="true"
   * @generated
   */
  AttributeType getAttributeType();

  /**
   * Sets the value of the '{@link org.xtext.tcc.mydsl.myDsl.Attribute#getAttributeType <em>Attribute Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Type</em>' containment reference.
   * @see #getAttributeType()
   * @generated
   */
  void setAttributeType(AttributeType value);

  /**
   * Returns the value of the '<em><b>Decision Get</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decision Get</em>' containment reference.
   * @see #setDecisionGet(Bool)
   * @see org.xtext.tcc.mydsl.myDsl.MyDslPackage#getAttribute_DecisionGet()
   * @model containment="true"
   * @generated
   */
  Bool getDecisionGet();

  /**
   * Sets the value of the '{@link org.xtext.tcc.mydsl.myDsl.Attribute#getDecisionGet <em>Decision Get</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decision Get</em>' containment reference.
   * @see #getDecisionGet()
   * @generated
   */
  void setDecisionGet(Bool value);

  /**
   * Returns the value of the '<em><b>Decision Set</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decision Set</em>' containment reference.
   * @see #setDecisionSet(Bool)
   * @see org.xtext.tcc.mydsl.myDsl.MyDslPackage#getAttribute_DecisionSet()
   * @model containment="true"
   * @generated
   */
  Bool getDecisionSet();

  /**
   * Sets the value of the '{@link org.xtext.tcc.mydsl.myDsl.Attribute#getDecisionSet <em>Decision Set</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decision Set</em>' containment reference.
   * @see #getDecisionSet()
   * @generated
   */
  void setDecisionSet(Bool value);

  /**
   * Returns the value of the '<em><b>Decision ID</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decision ID</em>' containment reference.
   * @see #setDecisionID(Bool)
   * @see org.xtext.tcc.mydsl.myDsl.MyDslPackage#getAttribute_DecisionID()
   * @model containment="true"
   * @generated
   */
  Bool getDecisionID();

  /**
   * Sets the value of the '{@link org.xtext.tcc.mydsl.myDsl.Attribute#getDecisionID <em>Decision ID</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decision ID</em>' containment reference.
   * @see #getDecisionID()
   * @generated
   */
  void setDecisionID(Bool value);

} // Attribute
