/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.tcc.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.tcc.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/tcc/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Greetings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GREETINGS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.GreetingImpl <em>Greeting</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.GreetingImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getGreeting()
   * @generated
   */
  int GREETING = 1;

  /**
   * The feature id for the '<em><b>Api</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREETING__API = 0;

  /**
   * The number of structural features of the '<em>Greeting</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREETING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.ApiImpl <em>Api</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.ApiImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getApi()
   * @generated
   */
  int API = 2;

  /**
   * The feature id for the '<em><b>Nome Api</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int API__NOME_API = 0;

  /**
   * The feature id for the '<em><b>Entidades</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int API__ENTIDADES = 1;

  /**
   * The number of structural features of the '<em>Api</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int API_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.ApiNomeImpl <em>Api Nome</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.ApiNomeImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getApiNome()
   * @generated
   */
  int API_NOME = 3;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int API_NOME__ID = 0;

  /**
   * The number of structural features of the '<em>Api Nome</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int API_NOME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.EntidadeImpl <em>Entidade</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.EntidadeImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getEntidade()
   * @generated
   */
  int ENTIDADE = 4;

  /**
   * The feature id for the '<em><b>Nome Entidade</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDADE__NOME_ENTIDADE = 0;

  /**
   * The feature id for the '<em><b>Atributo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDADE__ATRIBUTO = 1;

  /**
   * The number of structural features of the '<em>Entidade</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDADE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.EntidadeNomeImpl <em>Entidade Nome</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.EntidadeNomeImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getEntidadeNome()
   * @generated
   */
  int ENTIDADE_NOME = 5;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDADE_NOME__ID = 0;

  /**
   * The number of structural features of the '<em>Entidade Nome</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDADE_NOME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl <em>Atributo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getAtributo()
   * @generated
   */
  int ATRIBUTO = 6;

  /**
   * The feature id for the '<em><b>Atributo Nome</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__ATRIBUTO_NOME = 0;

  /**
   * The feature id for the '<em><b>Atributo Tipo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__ATRIBUTO_TIPO = 1;

  /**
   * The feature id for the '<em><b>Associacao Nome</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__ASSOCIACAO_NOME = 2;

  /**
   * The feature id for the '<em><b>Operacao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__OPERACAO = 3;

  /**
   * The feature id for the '<em><b>Nome Entidade</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__NOME_ENTIDADE = 4;

  /**
   * The feature id for the '<em><b>Tabela Nome</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__TABELA_NOME = 5;

  /**
   * The feature id for the '<em><b>Coluna Nome</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__COLUNA_NOME = 6;

  /**
   * The feature id for the '<em><b>Coluna Nome Inverse</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__COLUNA_NOME_INVERSE = 7;

  /**
   * The number of structural features of the '<em>Atributo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.ColunaNomeImpl <em>Coluna Nome</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.ColunaNomeImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getColunaNome()
   * @generated
   */
  int COLUNA_NOME = 7;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUNA_NOME__ID = 0;

  /**
   * The number of structural features of the '<em>Coluna Nome</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUNA_NOME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.TabelaNomeImpl <em>Tabela Nome</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.TabelaNomeImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getTabelaNome()
   * @generated
   */
  int TABELA_NOME = 8;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABELA_NOME__ID = 0;

  /**
   * The number of structural features of the '<em>Tabela Nome</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABELA_NOME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.OperacaoImpl <em>Operacao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.OperacaoImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getOperacao()
   * @generated
   */
  int OPERACAO = 9;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERACAO__ID = 0;

  /**
   * The number of structural features of the '<em>Operacao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERACAO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.AssociacaoNomeImpl <em>Associacao Nome</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.AssociacaoNomeImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getAssociacaoNome()
   * @generated
   */
  int ASSOCIACAO_NOME = 10;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIACAO_NOME__ID = 0;

  /**
   * The number of structural features of the '<em>Associacao Nome</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIACAO_NOME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoNomeImpl <em>Atributo Nome</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.AtributoNomeImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getAtributoNome()
   * @generated
   */
  int ATRIBUTO_NOME = 11;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO_NOME__ID = 0;

  /**
   * The number of structural features of the '<em>Atributo Nome</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO_NOME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoTipoImpl <em>Atributo Tipo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tcc.mydsl.myDsl.impl.AtributoTipoImpl
   * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getAtributoTipo()
   * @generated
   */
  int ATRIBUTO_TIPO = 12;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO_TIPO__ID = 0;

  /**
   * The number of structural features of the '<em>Atributo Tipo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO_TIPO_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tcc.mydsl.myDsl.Model#getGreetings <em>Greetings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Greetings</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Model#getGreetings()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Greetings();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.Greeting <em>Greeting</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greeting</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Greeting
   * @generated
   */
  EClass getGreeting();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Greeting#getApi <em>Api</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Api</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Greeting#getApi()
   * @see #getGreeting()
   * @generated
   */
  EReference getGreeting_Api();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.Api <em>Api</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Api</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Api
   * @generated
   */
  EClass getApi();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Api#getNomeApi <em>Nome Api</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nome Api</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Api#getNomeApi()
   * @see #getApi()
   * @generated
   */
  EReference getApi_NomeApi();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tcc.mydsl.myDsl.Api#getEntidades <em>Entidades</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entidades</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Api#getEntidades()
   * @see #getApi()
   * @generated
   */
  EReference getApi_Entidades();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.ApiNome <em>Api Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Api Nome</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.ApiNome
   * @generated
   */
  EClass getApiNome();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tcc.mydsl.myDsl.ApiNome#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.ApiNome#getId()
   * @see #getApiNome()
   * @generated
   */
  EAttribute getApiNome_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.Entidade <em>Entidade</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidade</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Entidade
   * @generated
   */
  EClass getEntidade();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Entidade#getNomeEntidade <em>Nome Entidade</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nome Entidade</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Entidade#getNomeEntidade()
   * @see #getEntidade()
   * @generated
   */
  EReference getEntidade_NomeEntidade();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tcc.mydsl.myDsl.Entidade#getAtributo <em>Atributo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Atributo</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Entidade#getAtributo()
   * @see #getEntidade()
   * @generated
   */
  EReference getEntidade_Atributo();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.EntidadeNome <em>Entidade Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidade Nome</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.EntidadeNome
   * @generated
   */
  EClass getEntidadeNome();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tcc.mydsl.myDsl.EntidadeNome#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.EntidadeNome#getId()
   * @see #getEntidadeNome()
   * @generated
   */
  EAttribute getEntidadeNome_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.Atributo <em>Atributo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atributo</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Atributo
   * @generated
   */
  EClass getAtributo();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Atributo#getAtributoNome <em>Atributo Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atributo Nome</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Atributo#getAtributoNome()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_AtributoNome();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Atributo#getAtributoTipo <em>Atributo Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atributo Tipo</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Atributo#getAtributoTipo()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_AtributoTipo();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Atributo#getAssociacaoNome <em>Associacao Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Associacao Nome</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Atributo#getAssociacaoNome()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_AssociacaoNome();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Atributo#getOperacao <em>Operacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operacao</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Atributo#getOperacao()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_Operacao();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Atributo#getNomeEntidade <em>Nome Entidade</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nome Entidade</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Atributo#getNomeEntidade()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_NomeEntidade();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Atributo#getTabelaNome <em>Tabela Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tabela Nome</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Atributo#getTabelaNome()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_TabelaNome();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Atributo#getColunaNome <em>Coluna Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coluna Nome</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Atributo#getColunaNome()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_ColunaNome();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tcc.mydsl.myDsl.Atributo#getColunaNomeInverse <em>Coluna Nome Inverse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coluna Nome Inverse</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Atributo#getColunaNomeInverse()
   * @see #getAtributo()
   * @generated
   */
  EReference getAtributo_ColunaNomeInverse();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.ColunaNome <em>Coluna Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coluna Nome</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.ColunaNome
   * @generated
   */
  EClass getColunaNome();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tcc.mydsl.myDsl.ColunaNome#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.ColunaNome#getId()
   * @see #getColunaNome()
   * @generated
   */
  EAttribute getColunaNome_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.TabelaNome <em>Tabela Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tabela Nome</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.TabelaNome
   * @generated
   */
  EClass getTabelaNome();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tcc.mydsl.myDsl.TabelaNome#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.TabelaNome#getId()
   * @see #getTabelaNome()
   * @generated
   */
  EAttribute getTabelaNome_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.Operacao <em>Operacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operacao</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Operacao
   * @generated
   */
  EClass getOperacao();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tcc.mydsl.myDsl.Operacao#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.Operacao#getId()
   * @see #getOperacao()
   * @generated
   */
  EAttribute getOperacao_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.AssociacaoNome <em>Associacao Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Associacao Nome</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.AssociacaoNome
   * @generated
   */
  EClass getAssociacaoNome();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tcc.mydsl.myDsl.AssociacaoNome#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.AssociacaoNome#getId()
   * @see #getAssociacaoNome()
   * @generated
   */
  EAttribute getAssociacaoNome_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.AtributoNome <em>Atributo Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atributo Nome</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.AtributoNome
   * @generated
   */
  EClass getAtributoNome();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tcc.mydsl.myDsl.AtributoNome#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.AtributoNome#getId()
   * @see #getAtributoNome()
   * @generated
   */
  EAttribute getAtributoNome_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.tcc.mydsl.myDsl.AtributoTipo <em>Atributo Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atributo Tipo</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.AtributoTipo
   * @generated
   */
  EClass getAtributoTipo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tcc.mydsl.myDsl.AtributoTipo#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.tcc.mydsl.myDsl.AtributoTipo#getId()
   * @see #getAtributoTipo()
   * @generated
   */
  EAttribute getAtributoTipo_Id();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Greetings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GREETINGS = eINSTANCE.getModel_Greetings();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.GreetingImpl <em>Greeting</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.GreetingImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getGreeting()
     * @generated
     */
    EClass GREETING = eINSTANCE.getGreeting();

    /**
     * The meta object literal for the '<em><b>Api</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREETING__API = eINSTANCE.getGreeting_Api();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.ApiImpl <em>Api</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.ApiImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getApi()
     * @generated
     */
    EClass API = eINSTANCE.getApi();

    /**
     * The meta object literal for the '<em><b>Nome Api</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference API__NOME_API = eINSTANCE.getApi_NomeApi();

    /**
     * The meta object literal for the '<em><b>Entidades</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference API__ENTIDADES = eINSTANCE.getApi_Entidades();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.ApiNomeImpl <em>Api Nome</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.ApiNomeImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getApiNome()
     * @generated
     */
    EClass API_NOME = eINSTANCE.getApiNome();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute API_NOME__ID = eINSTANCE.getApiNome_Id();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.EntidadeImpl <em>Entidade</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.EntidadeImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getEntidade()
     * @generated
     */
    EClass ENTIDADE = eINSTANCE.getEntidade();

    /**
     * The meta object literal for the '<em><b>Nome Entidade</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTIDADE__NOME_ENTIDADE = eINSTANCE.getEntidade_NomeEntidade();

    /**
     * The meta object literal for the '<em><b>Atributo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTIDADE__ATRIBUTO = eINSTANCE.getEntidade_Atributo();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.EntidadeNomeImpl <em>Entidade Nome</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.EntidadeNomeImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getEntidadeNome()
     * @generated
     */
    EClass ENTIDADE_NOME = eINSTANCE.getEntidadeNome();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTIDADE_NOME__ID = eINSTANCE.getEntidadeNome_Id();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl <em>Atributo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getAtributo()
     * @generated
     */
    EClass ATRIBUTO = eINSTANCE.getAtributo();

    /**
     * The meta object literal for the '<em><b>Atributo Nome</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__ATRIBUTO_NOME = eINSTANCE.getAtributo_AtributoNome();

    /**
     * The meta object literal for the '<em><b>Atributo Tipo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__ATRIBUTO_TIPO = eINSTANCE.getAtributo_AtributoTipo();

    /**
     * The meta object literal for the '<em><b>Associacao Nome</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__ASSOCIACAO_NOME = eINSTANCE.getAtributo_AssociacaoNome();

    /**
     * The meta object literal for the '<em><b>Operacao</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__OPERACAO = eINSTANCE.getAtributo_Operacao();

    /**
     * The meta object literal for the '<em><b>Nome Entidade</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__NOME_ENTIDADE = eINSTANCE.getAtributo_NomeEntidade();

    /**
     * The meta object literal for the '<em><b>Tabela Nome</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__TABELA_NOME = eINSTANCE.getAtributo_TabelaNome();

    /**
     * The meta object literal for the '<em><b>Coluna Nome</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__COLUNA_NOME = eINSTANCE.getAtributo_ColunaNome();

    /**
     * The meta object literal for the '<em><b>Coluna Nome Inverse</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUTO__COLUNA_NOME_INVERSE = eINSTANCE.getAtributo_ColunaNomeInverse();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.ColunaNomeImpl <em>Coluna Nome</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.ColunaNomeImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getColunaNome()
     * @generated
     */
    EClass COLUNA_NOME = eINSTANCE.getColunaNome();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUNA_NOME__ID = eINSTANCE.getColunaNome_Id();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.TabelaNomeImpl <em>Tabela Nome</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.TabelaNomeImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getTabelaNome()
     * @generated
     */
    EClass TABELA_NOME = eINSTANCE.getTabelaNome();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABELA_NOME__ID = eINSTANCE.getTabelaNome_Id();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.OperacaoImpl <em>Operacao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.OperacaoImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getOperacao()
     * @generated
     */
    EClass OPERACAO = eINSTANCE.getOperacao();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERACAO__ID = eINSTANCE.getOperacao_Id();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.AssociacaoNomeImpl <em>Associacao Nome</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.AssociacaoNomeImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getAssociacaoNome()
     * @generated
     */
    EClass ASSOCIACAO_NOME = eINSTANCE.getAssociacaoNome();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSOCIACAO_NOME__ID = eINSTANCE.getAssociacaoNome_Id();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoNomeImpl <em>Atributo Nome</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.AtributoNomeImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getAtributoNome()
     * @generated
     */
    EClass ATRIBUTO_NOME = eINSTANCE.getAtributoNome();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUTO_NOME__ID = eINSTANCE.getAtributoNome_Id();

    /**
     * The meta object literal for the '{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoTipoImpl <em>Atributo Tipo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tcc.mydsl.myDsl.impl.AtributoTipoImpl
     * @see org.xtext.tcc.mydsl.myDsl.impl.MyDslPackageImpl#getAtributoTipo()
     * @generated
     */
    EClass ATRIBUTO_TIPO = eINSTANCE.getAtributoTipo();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUTO_TIPO__ID = eINSTANCE.getAtributoTipo_Id();

  }

} //MyDslPackage
