/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.tcc.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operacao Cascada</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.OperacaoCascada#getOperacao <em>Operacao</em>}</li>
 * </ul>
 *
 * @see org.xtext.tcc.mydsl.myDsl.MyDslPackage#getOperacaoCascada()
 * @model
 * @generated
 */
public interface OperacaoCascada extends EObject
{
  /**
   * Returns the value of the '<em><b>Operacao</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operacao</em>' attribute.
   * @see #setOperacao(String)
   * @see org.xtext.tcc.mydsl.myDsl.MyDslPackage#getOperacaoCascada_Operacao()
   * @model
   * @generated
   */
  String getOperacao();

  /**
   * Sets the value of the '{@link org.xtext.tcc.mydsl.myDsl.OperacaoCascada#getOperacao <em>Operacao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operacao</em>' attribute.
   * @see #getOperacao()
   * @generated
   */
  void setOperacao(String value);

} // OperacaoCascada
