/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.tcc.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tcc.mydsl.myDsl.AtributoTipo;
import org.xtext.tcc.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atributo Tipo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoTipoImpl#getTipoPrimitivo <em>Tipo Primitivo</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoTipoImpl#getTipoColecao <em>Tipo Colecao</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoTipoImpl#getTipoObjeto <em>Tipo Objeto</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtributoTipoImpl extends MinimalEObjectImpl.Container implements AtributoTipo
{
  /**
   * The default value of the '{@link #getTipoPrimitivo() <em>Tipo Primitivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoPrimitivo()
   * @generated
   * @ordered
   */
  protected static final String TIPO_PRIMITIVO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTipoPrimitivo() <em>Tipo Primitivo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoPrimitivo()
   * @generated
   * @ordered
   */
  protected String tipoPrimitivo = TIPO_PRIMITIVO_EDEFAULT;

  /**
   * The default value of the '{@link #getTipoColecao() <em>Tipo Colecao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoColecao()
   * @generated
   * @ordered
   */
  protected static final String TIPO_COLECAO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTipoColecao() <em>Tipo Colecao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoColecao()
   * @generated
   * @ordered
   */
  protected String tipoColecao = TIPO_COLECAO_EDEFAULT;

  /**
   * The default value of the '{@link #getTipoObjeto() <em>Tipo Objeto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoObjeto()
   * @generated
   * @ordered
   */
  protected static final String TIPO_OBJETO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTipoObjeto() <em>Tipo Objeto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoObjeto()
   * @generated
   * @ordered
   */
  protected String tipoObjeto = TIPO_OBJETO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtributoTipoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ATRIBUTO_TIPO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTipoPrimitivo()
  {
    return tipoPrimitivo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoPrimitivo(String newTipoPrimitivo)
  {
    String oldTipoPrimitivo = tipoPrimitivo;
    tipoPrimitivo = newTipoPrimitivo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO_TIPO__TIPO_PRIMITIVO, oldTipoPrimitivo, tipoPrimitivo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTipoColecao()
  {
    return tipoColecao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoColecao(String newTipoColecao)
  {
    String oldTipoColecao = tipoColecao;
    tipoColecao = newTipoColecao;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO_TIPO__TIPO_COLECAO, oldTipoColecao, tipoColecao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTipoObjeto()
  {
    return tipoObjeto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoObjeto(String newTipoObjeto)
  {
    String oldTipoObjeto = tipoObjeto;
    tipoObjeto = newTipoObjeto;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO_TIPO__TIPO_OBJETO, oldTipoObjeto, tipoObjeto));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_PRIMITIVO:
        return getTipoPrimitivo();
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_COLECAO:
        return getTipoColecao();
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_OBJETO:
        return getTipoObjeto();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_PRIMITIVO:
        setTipoPrimitivo((String)newValue);
        return;
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_COLECAO:
        setTipoColecao((String)newValue);
        return;
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_OBJETO:
        setTipoObjeto((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_PRIMITIVO:
        setTipoPrimitivo(TIPO_PRIMITIVO_EDEFAULT);
        return;
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_COLECAO:
        setTipoColecao(TIPO_COLECAO_EDEFAULT);
        return;
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_OBJETO:
        setTipoObjeto(TIPO_OBJETO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_PRIMITIVO:
        return TIPO_PRIMITIVO_EDEFAULT == null ? tipoPrimitivo != null : !TIPO_PRIMITIVO_EDEFAULT.equals(tipoPrimitivo);
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_COLECAO:
        return TIPO_COLECAO_EDEFAULT == null ? tipoColecao != null : !TIPO_COLECAO_EDEFAULT.equals(tipoColecao);
      case MyDslPackage.ATRIBUTO_TIPO__TIPO_OBJETO:
        return TIPO_OBJETO_EDEFAULT == null ? tipoObjeto != null : !TIPO_OBJETO_EDEFAULT.equals(tipoObjeto);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (tipoPrimitivo: ");
    result.append(tipoPrimitivo);
    result.append(", tipoColecao: ");
    result.append(tipoColecao);
    result.append(", tipoObjeto: ");
    result.append(tipoObjeto);
    result.append(')');
    return result.toString();
  }

} //AtributoTipoImpl
