/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.tcc.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tcc.mydsl.myDsl.Associacao;
import org.xtext.tcc.mydsl.myDsl.Atributo;
import org.xtext.tcc.mydsl.myDsl.AtributoNome;
import org.xtext.tcc.mydsl.myDsl.AtributoTipo;
import org.xtext.tcc.mydsl.myDsl.ChavePrimaria;
import org.xtext.tcc.mydsl.myDsl.ColunaNome;
import org.xtext.tcc.mydsl.myDsl.MyDslPackage;
import org.xtext.tcc.mydsl.myDsl.Operacao;
import org.xtext.tcc.mydsl.myDsl.Optional;
import org.xtext.tcc.mydsl.myDsl.TabelaNome;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atributo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl#getAtributoNome <em>Atributo Nome</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl#getAtributoTipo <em>Atributo Tipo</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl#getAssociacao <em>Associacao</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl#getOperacao <em>Operacao</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl#getOptional <em>Optional</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl#getTabelaNome <em>Tabela Nome</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl#getColunaNome <em>Coluna Nome</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl#getColunaNomeInverse <em>Coluna Nome Inverse</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AtributoImpl#getChavePrimaria <em>Chave Primaria</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtributoImpl extends MinimalEObjectImpl.Container implements Atributo
{
  /**
   * The cached value of the '{@link #getAtributoNome() <em>Atributo Nome</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtributoNome()
   * @generated
   * @ordered
   */
  protected AtributoNome atributoNome;

  /**
   * The cached value of the '{@link #getAtributoTipo() <em>Atributo Tipo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtributoTipo()
   * @generated
   * @ordered
   */
  protected AtributoTipo atributoTipo;

  /**
   * The cached value of the '{@link #getAssociacao() <em>Associacao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAssociacao()
   * @generated
   * @ordered
   */
  protected Associacao associacao;

  /**
   * The cached value of the '{@link #getOperacao() <em>Operacao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperacao()
   * @generated
   * @ordered
   */
  protected Operacao operacao;

  /**
   * The cached value of the '{@link #getOptional() <em>Optional</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOptional()
   * @generated
   * @ordered
   */
  protected Optional optional;

  /**
   * The cached value of the '{@link #getTabelaNome() <em>Tabela Nome</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTabelaNome()
   * @generated
   * @ordered
   */
  protected TabelaNome tabelaNome;

  /**
   * The cached value of the '{@link #getColunaNome() <em>Coluna Nome</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColunaNome()
   * @generated
   * @ordered
   */
  protected ColunaNome colunaNome;

  /**
   * The cached value of the '{@link #getColunaNomeInverse() <em>Coluna Nome Inverse</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColunaNomeInverse()
   * @generated
   * @ordered
   */
  protected ColunaNome colunaNomeInverse;

  /**
   * The cached value of the '{@link #getChavePrimaria() <em>Chave Primaria</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChavePrimaria()
   * @generated
   * @ordered
   */
  protected ChavePrimaria chavePrimaria;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtributoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ATRIBUTO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtributoNome getAtributoNome()
  {
    return atributoNome;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtributoNome(AtributoNome newAtributoNome, NotificationChain msgs)
  {
    AtributoNome oldAtributoNome = atributoNome;
    atributoNome = newAtributoNome;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__ATRIBUTO_NOME, oldAtributoNome, newAtributoNome);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAtributoNome(AtributoNome newAtributoNome)
  {
    if (newAtributoNome != atributoNome)
    {
      NotificationChain msgs = null;
      if (atributoNome != null)
        msgs = ((InternalEObject)atributoNome).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__ATRIBUTO_NOME, null, msgs);
      if (newAtributoNome != null)
        msgs = ((InternalEObject)newAtributoNome).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__ATRIBUTO_NOME, null, msgs);
      msgs = basicSetAtributoNome(newAtributoNome, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__ATRIBUTO_NOME, newAtributoNome, newAtributoNome));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtributoTipo getAtributoTipo()
  {
    return atributoTipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtributoTipo(AtributoTipo newAtributoTipo, NotificationChain msgs)
  {
    AtributoTipo oldAtributoTipo = atributoTipo;
    atributoTipo = newAtributoTipo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__ATRIBUTO_TIPO, oldAtributoTipo, newAtributoTipo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAtributoTipo(AtributoTipo newAtributoTipo)
  {
    if (newAtributoTipo != atributoTipo)
    {
      NotificationChain msgs = null;
      if (atributoTipo != null)
        msgs = ((InternalEObject)atributoTipo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__ATRIBUTO_TIPO, null, msgs);
      if (newAtributoTipo != null)
        msgs = ((InternalEObject)newAtributoTipo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__ATRIBUTO_TIPO, null, msgs);
      msgs = basicSetAtributoTipo(newAtributoTipo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__ATRIBUTO_TIPO, newAtributoTipo, newAtributoTipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Associacao getAssociacao()
  {
    return associacao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAssociacao(Associacao newAssociacao, NotificationChain msgs)
  {
    Associacao oldAssociacao = associacao;
    associacao = newAssociacao;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__ASSOCIACAO, oldAssociacao, newAssociacao);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAssociacao(Associacao newAssociacao)
  {
    if (newAssociacao != associacao)
    {
      NotificationChain msgs = null;
      if (associacao != null)
        msgs = ((InternalEObject)associacao).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__ASSOCIACAO, null, msgs);
      if (newAssociacao != null)
        msgs = ((InternalEObject)newAssociacao).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__ASSOCIACAO, null, msgs);
      msgs = basicSetAssociacao(newAssociacao, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__ASSOCIACAO, newAssociacao, newAssociacao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operacao getOperacao()
  {
    return operacao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOperacao(Operacao newOperacao, NotificationChain msgs)
  {
    Operacao oldOperacao = operacao;
    operacao = newOperacao;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__OPERACAO, oldOperacao, newOperacao);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperacao(Operacao newOperacao)
  {
    if (newOperacao != operacao)
    {
      NotificationChain msgs = null;
      if (operacao != null)
        msgs = ((InternalEObject)operacao).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__OPERACAO, null, msgs);
      if (newOperacao != null)
        msgs = ((InternalEObject)newOperacao).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__OPERACAO, null, msgs);
      msgs = basicSetOperacao(newOperacao, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__OPERACAO, newOperacao, newOperacao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Optional getOptional()
  {
    return optional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOptional(Optional newOptional, NotificationChain msgs)
  {
    Optional oldOptional = optional;
    optional = newOptional;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__OPTIONAL, oldOptional, newOptional);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOptional(Optional newOptional)
  {
    if (newOptional != optional)
    {
      NotificationChain msgs = null;
      if (optional != null)
        msgs = ((InternalEObject)optional).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__OPTIONAL, null, msgs);
      if (newOptional != null)
        msgs = ((InternalEObject)newOptional).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__OPTIONAL, null, msgs);
      msgs = basicSetOptional(newOptional, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__OPTIONAL, newOptional, newOptional));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TabelaNome getTabelaNome()
  {
    return tabelaNome;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTabelaNome(TabelaNome newTabelaNome, NotificationChain msgs)
  {
    TabelaNome oldTabelaNome = tabelaNome;
    tabelaNome = newTabelaNome;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__TABELA_NOME, oldTabelaNome, newTabelaNome);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTabelaNome(TabelaNome newTabelaNome)
  {
    if (newTabelaNome != tabelaNome)
    {
      NotificationChain msgs = null;
      if (tabelaNome != null)
        msgs = ((InternalEObject)tabelaNome).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__TABELA_NOME, null, msgs);
      if (newTabelaNome != null)
        msgs = ((InternalEObject)newTabelaNome).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__TABELA_NOME, null, msgs);
      msgs = basicSetTabelaNome(newTabelaNome, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__TABELA_NOME, newTabelaNome, newTabelaNome));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ColunaNome getColunaNome()
  {
    return colunaNome;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetColunaNome(ColunaNome newColunaNome, NotificationChain msgs)
  {
    ColunaNome oldColunaNome = colunaNome;
    colunaNome = newColunaNome;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__COLUNA_NOME, oldColunaNome, newColunaNome);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColunaNome(ColunaNome newColunaNome)
  {
    if (newColunaNome != colunaNome)
    {
      NotificationChain msgs = null;
      if (colunaNome != null)
        msgs = ((InternalEObject)colunaNome).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__COLUNA_NOME, null, msgs);
      if (newColunaNome != null)
        msgs = ((InternalEObject)newColunaNome).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__COLUNA_NOME, null, msgs);
      msgs = basicSetColunaNome(newColunaNome, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__COLUNA_NOME, newColunaNome, newColunaNome));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ColunaNome getColunaNomeInverse()
  {
    return colunaNomeInverse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetColunaNomeInverse(ColunaNome newColunaNomeInverse, NotificationChain msgs)
  {
    ColunaNome oldColunaNomeInverse = colunaNomeInverse;
    colunaNomeInverse = newColunaNomeInverse;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__COLUNA_NOME_INVERSE, oldColunaNomeInverse, newColunaNomeInverse);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColunaNomeInverse(ColunaNome newColunaNomeInverse)
  {
    if (newColunaNomeInverse != colunaNomeInverse)
    {
      NotificationChain msgs = null;
      if (colunaNomeInverse != null)
        msgs = ((InternalEObject)colunaNomeInverse).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__COLUNA_NOME_INVERSE, null, msgs);
      if (newColunaNomeInverse != null)
        msgs = ((InternalEObject)newColunaNomeInverse).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__COLUNA_NOME_INVERSE, null, msgs);
      msgs = basicSetColunaNomeInverse(newColunaNomeInverse, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__COLUNA_NOME_INVERSE, newColunaNomeInverse, newColunaNomeInverse));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ChavePrimaria getChavePrimaria()
  {
    return chavePrimaria;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetChavePrimaria(ChavePrimaria newChavePrimaria, NotificationChain msgs)
  {
    ChavePrimaria oldChavePrimaria = chavePrimaria;
    chavePrimaria = newChavePrimaria;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__CHAVE_PRIMARIA, oldChavePrimaria, newChavePrimaria);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setChavePrimaria(ChavePrimaria newChavePrimaria)
  {
    if (newChavePrimaria != chavePrimaria)
    {
      NotificationChain msgs = null;
      if (chavePrimaria != null)
        msgs = ((InternalEObject)chavePrimaria).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__CHAVE_PRIMARIA, null, msgs);
      if (newChavePrimaria != null)
        msgs = ((InternalEObject)newChavePrimaria).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATRIBUTO__CHAVE_PRIMARIA, null, msgs);
      msgs = basicSetChavePrimaria(newChavePrimaria, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATRIBUTO__CHAVE_PRIMARIA, newChavePrimaria, newChavePrimaria));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ATRIBUTO__ATRIBUTO_NOME:
        return basicSetAtributoNome(null, msgs);
      case MyDslPackage.ATRIBUTO__ATRIBUTO_TIPO:
        return basicSetAtributoTipo(null, msgs);
      case MyDslPackage.ATRIBUTO__ASSOCIACAO:
        return basicSetAssociacao(null, msgs);
      case MyDslPackage.ATRIBUTO__OPERACAO:
        return basicSetOperacao(null, msgs);
      case MyDslPackage.ATRIBUTO__OPTIONAL:
        return basicSetOptional(null, msgs);
      case MyDslPackage.ATRIBUTO__TABELA_NOME:
        return basicSetTabelaNome(null, msgs);
      case MyDslPackage.ATRIBUTO__COLUNA_NOME:
        return basicSetColunaNome(null, msgs);
      case MyDslPackage.ATRIBUTO__COLUNA_NOME_INVERSE:
        return basicSetColunaNomeInverse(null, msgs);
      case MyDslPackage.ATRIBUTO__CHAVE_PRIMARIA:
        return basicSetChavePrimaria(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ATRIBUTO__ATRIBUTO_NOME:
        return getAtributoNome();
      case MyDslPackage.ATRIBUTO__ATRIBUTO_TIPO:
        return getAtributoTipo();
      case MyDslPackage.ATRIBUTO__ASSOCIACAO:
        return getAssociacao();
      case MyDslPackage.ATRIBUTO__OPERACAO:
        return getOperacao();
      case MyDslPackage.ATRIBUTO__OPTIONAL:
        return getOptional();
      case MyDslPackage.ATRIBUTO__TABELA_NOME:
        return getTabelaNome();
      case MyDslPackage.ATRIBUTO__COLUNA_NOME:
        return getColunaNome();
      case MyDslPackage.ATRIBUTO__COLUNA_NOME_INVERSE:
        return getColunaNomeInverse();
      case MyDslPackage.ATRIBUTO__CHAVE_PRIMARIA:
        return getChavePrimaria();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ATRIBUTO__ATRIBUTO_NOME:
        setAtributoNome((AtributoNome)newValue);
        return;
      case MyDslPackage.ATRIBUTO__ATRIBUTO_TIPO:
        setAtributoTipo((AtributoTipo)newValue);
        return;
      case MyDslPackage.ATRIBUTO__ASSOCIACAO:
        setAssociacao((Associacao)newValue);
        return;
      case MyDslPackage.ATRIBUTO__OPERACAO:
        setOperacao((Operacao)newValue);
        return;
      case MyDslPackage.ATRIBUTO__OPTIONAL:
        setOptional((Optional)newValue);
        return;
      case MyDslPackage.ATRIBUTO__TABELA_NOME:
        setTabelaNome((TabelaNome)newValue);
        return;
      case MyDslPackage.ATRIBUTO__COLUNA_NOME:
        setColunaNome((ColunaNome)newValue);
        return;
      case MyDslPackage.ATRIBUTO__COLUNA_NOME_INVERSE:
        setColunaNomeInverse((ColunaNome)newValue);
        return;
      case MyDslPackage.ATRIBUTO__CHAVE_PRIMARIA:
        setChavePrimaria((ChavePrimaria)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ATRIBUTO__ATRIBUTO_NOME:
        setAtributoNome((AtributoNome)null);
        return;
      case MyDslPackage.ATRIBUTO__ATRIBUTO_TIPO:
        setAtributoTipo((AtributoTipo)null);
        return;
      case MyDslPackage.ATRIBUTO__ASSOCIACAO:
        setAssociacao((Associacao)null);
        return;
      case MyDslPackage.ATRIBUTO__OPERACAO:
        setOperacao((Operacao)null);
        return;
      case MyDslPackage.ATRIBUTO__OPTIONAL:
        setOptional((Optional)null);
        return;
      case MyDslPackage.ATRIBUTO__TABELA_NOME:
        setTabelaNome((TabelaNome)null);
        return;
      case MyDslPackage.ATRIBUTO__COLUNA_NOME:
        setColunaNome((ColunaNome)null);
        return;
      case MyDslPackage.ATRIBUTO__COLUNA_NOME_INVERSE:
        setColunaNomeInverse((ColunaNome)null);
        return;
      case MyDslPackage.ATRIBUTO__CHAVE_PRIMARIA:
        setChavePrimaria((ChavePrimaria)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ATRIBUTO__ATRIBUTO_NOME:
        return atributoNome != null;
      case MyDslPackage.ATRIBUTO__ATRIBUTO_TIPO:
        return atributoTipo != null;
      case MyDslPackage.ATRIBUTO__ASSOCIACAO:
        return associacao != null;
      case MyDslPackage.ATRIBUTO__OPERACAO:
        return operacao != null;
      case MyDslPackage.ATRIBUTO__OPTIONAL:
        return optional != null;
      case MyDslPackage.ATRIBUTO__TABELA_NOME:
        return tabelaNome != null;
      case MyDslPackage.ATRIBUTO__COLUNA_NOME:
        return colunaNome != null;
      case MyDslPackage.ATRIBUTO__COLUNA_NOME_INVERSE:
        return colunaNomeInverse != null;
      case MyDslPackage.ATRIBUTO__CHAVE_PRIMARIA:
        return chavePrimaria != null;
    }
    return super.eIsSet(featureID);
  }

} //AtributoImpl
