/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.tcc.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.tcc.mydsl.myDsl.Attribute;
import org.xtext.tcc.mydsl.myDsl.AttributeName;
import org.xtext.tcc.mydsl.myDsl.AttributeType;
import org.xtext.tcc.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AttributeImpl#getAttributeName <em>Attribute Name</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AttributeImpl#getAttributeType <em>Attribute Type</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AttributeImpl#getDecisionGet <em>Decision Get</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AttributeImpl#getDecisionSet <em>Decision Set</em>}</li>
 *   <li>{@link org.xtext.tcc.mydsl.myDsl.impl.AttributeImpl#getDecisionID <em>Decision ID</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeImpl extends MinimalEObjectImpl.Container implements Attribute
{
  /**
   * The cached value of the '{@link #getAttributeName() <em>Attribute Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttributeName()
   * @generated
   * @ordered
   */
  protected AttributeName attributeName;

  /**
   * The cached value of the '{@link #getAttributeType() <em>Attribute Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttributeType()
   * @generated
   * @ordered
   */
  protected AttributeType attributeType;

  /**
   * The default value of the '{@link #getDecisionGet() <em>Decision Get</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecisionGet()
   * @generated
   * @ordered
   */
  protected static final String DECISION_GET_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDecisionGet() <em>Decision Get</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecisionGet()
   * @generated
   * @ordered
   */
  protected String decisionGet = DECISION_GET_EDEFAULT;

  /**
   * The default value of the '{@link #getDecisionSet() <em>Decision Set</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecisionSet()
   * @generated
   * @ordered
   */
  protected static final String DECISION_SET_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDecisionSet() <em>Decision Set</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecisionSet()
   * @generated
   * @ordered
   */
  protected String decisionSet = DECISION_SET_EDEFAULT;

  /**
   * The default value of the '{@link #getDecisionID() <em>Decision ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecisionID()
   * @generated
   * @ordered
   */
  protected static final String DECISION_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDecisionID() <em>Decision ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecisionID()
   * @generated
   * @ordered
   */
  protected String decisionID = DECISION_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ATTRIBUTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AttributeName getAttributeName()
  {
    return attributeName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttributeName(AttributeName newAttributeName, NotificationChain msgs)
  {
    AttributeName oldAttributeName = attributeName;
    attributeName = newAttributeName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATTRIBUTE__ATTRIBUTE_NAME, oldAttributeName, newAttributeName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttributeName(AttributeName newAttributeName)
  {
    if (newAttributeName != attributeName)
    {
      NotificationChain msgs = null;
      if (attributeName != null)
        msgs = ((InternalEObject)attributeName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATTRIBUTE__ATTRIBUTE_NAME, null, msgs);
      if (newAttributeName != null)
        msgs = ((InternalEObject)newAttributeName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATTRIBUTE__ATTRIBUTE_NAME, null, msgs);
      msgs = basicSetAttributeName(newAttributeName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATTRIBUTE__ATTRIBUTE_NAME, newAttributeName, newAttributeName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AttributeType getAttributeType()
  {
    return attributeType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttributeType(AttributeType newAttributeType, NotificationChain msgs)
  {
    AttributeType oldAttributeType = attributeType;
    attributeType = newAttributeType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ATTRIBUTE__ATTRIBUTE_TYPE, oldAttributeType, newAttributeType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttributeType(AttributeType newAttributeType)
  {
    if (newAttributeType != attributeType)
    {
      NotificationChain msgs = null;
      if (attributeType != null)
        msgs = ((InternalEObject)attributeType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATTRIBUTE__ATTRIBUTE_TYPE, null, msgs);
      if (newAttributeType != null)
        msgs = ((InternalEObject)newAttributeType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ATTRIBUTE__ATTRIBUTE_TYPE, null, msgs);
      msgs = basicSetAttributeType(newAttributeType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATTRIBUTE__ATTRIBUTE_TYPE, newAttributeType, newAttributeType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDecisionGet()
  {
    return decisionGet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDecisionGet(String newDecisionGet)
  {
    String oldDecisionGet = decisionGet;
    decisionGet = newDecisionGet;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATTRIBUTE__DECISION_GET, oldDecisionGet, decisionGet));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDecisionSet()
  {
    return decisionSet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDecisionSet(String newDecisionSet)
  {
    String oldDecisionSet = decisionSet;
    decisionSet = newDecisionSet;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATTRIBUTE__DECISION_SET, oldDecisionSet, decisionSet));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDecisionID()
  {
    return decisionID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDecisionID(String newDecisionID)
  {
    String oldDecisionID = decisionID;
    decisionID = newDecisionID;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATTRIBUTE__DECISION_ID, oldDecisionID, decisionID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ATTRIBUTE__ATTRIBUTE_NAME:
        return basicSetAttributeName(null, msgs);
      case MyDslPackage.ATTRIBUTE__ATTRIBUTE_TYPE:
        return basicSetAttributeType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ATTRIBUTE__ATTRIBUTE_NAME:
        return getAttributeName();
      case MyDslPackage.ATTRIBUTE__ATTRIBUTE_TYPE:
        return getAttributeType();
      case MyDslPackage.ATTRIBUTE__DECISION_GET:
        return getDecisionGet();
      case MyDslPackage.ATTRIBUTE__DECISION_SET:
        return getDecisionSet();
      case MyDslPackage.ATTRIBUTE__DECISION_ID:
        return getDecisionID();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ATTRIBUTE__ATTRIBUTE_NAME:
        setAttributeName((AttributeName)newValue);
        return;
      case MyDslPackage.ATTRIBUTE__ATTRIBUTE_TYPE:
        setAttributeType((AttributeType)newValue);
        return;
      case MyDslPackage.ATTRIBUTE__DECISION_GET:
        setDecisionGet((String)newValue);
        return;
      case MyDslPackage.ATTRIBUTE__DECISION_SET:
        setDecisionSet((String)newValue);
        return;
      case MyDslPackage.ATTRIBUTE__DECISION_ID:
        setDecisionID((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ATTRIBUTE__ATTRIBUTE_NAME:
        setAttributeName((AttributeName)null);
        return;
      case MyDslPackage.ATTRIBUTE__ATTRIBUTE_TYPE:
        setAttributeType((AttributeType)null);
        return;
      case MyDslPackage.ATTRIBUTE__DECISION_GET:
        setDecisionGet(DECISION_GET_EDEFAULT);
        return;
      case MyDslPackage.ATTRIBUTE__DECISION_SET:
        setDecisionSet(DECISION_SET_EDEFAULT);
        return;
      case MyDslPackage.ATTRIBUTE__DECISION_ID:
        setDecisionID(DECISION_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ATTRIBUTE__ATTRIBUTE_NAME:
        return attributeName != null;
      case MyDslPackage.ATTRIBUTE__ATTRIBUTE_TYPE:
        return attributeType != null;
      case MyDslPackage.ATTRIBUTE__DECISION_GET:
        return DECISION_GET_EDEFAULT == null ? decisionGet != null : !DECISION_GET_EDEFAULT.equals(decisionGet);
      case MyDslPackage.ATTRIBUTE__DECISION_SET:
        return DECISION_SET_EDEFAULT == null ? decisionSet != null : !DECISION_SET_EDEFAULT.equals(decisionSet);
      case MyDslPackage.ATTRIBUTE__DECISION_ID:
        return DECISION_ID_EDEFAULT == null ? decisionID != null : !DECISION_ID_EDEFAULT.equals(decisionID);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (decisionGet: ");
    result.append(decisionGet);
    result.append(", decisionSet: ");
    result.append(decisionSet);
    result.append(", decisionID: ");
    result.append(decisionID);
    result.append(')');
    return result.toString();
  }

} //AttributeImpl
